language: swift
osx_image: xcode10.1

script:
  - set -o pipefail
  - xcodebuild -workspace Tracery.xcworkspace -scheme "Tracery iOS" build
  - # xcodebuild -project "Tracery/Tracery.xcodeproj" -scheme "Tracery iOS" -destination "platform=iOS Simulator,name=iPhone X" test

after_success:
  - bash <(curl -s https://codecov.io/bash)
